spring:
  devtools:
    restart:
      additional-paths: resources/**,static/**,templates/**,public/**
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8090