jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
logging:
  level:
    org:
      springframework:
        web: trace
eureka:
  instance:
    hostname: afrodita-grisk.herokuapp.com
    nonSecurePort: 80
    appname: afrodita
  client:
    serviceUrl:
      defaultZone: http://zeus.grisk.online/eureka/
management:
  health:
    ldap:
      enabled: false