jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
logging:
  level:
    org:
      springframework:
        web: trace
eureka:
  instance:
    hostname: www.grisk.online
    nonSecurePort: 80
    home-page-url: http://www.grisk.online
  client:
    serviceUrl:
      defaultZone: http://zeus.grisk.online/eureka/
    allow-redirects: true
management:
  health:
    ldap:
      enabled: false